### ISSUE TITLE
ccmake ../ failed because of duplicated target

### ISSUE THREAD

**Issue by sosuiming** [CollectiveTyranny/irrBullet#2]
target in:
examples/Vehicle/CMakeLists.txt
should be changed to, say, 'vehicle' instead of 'helloworld'

Part of cmake error log:
 CMake Error at examples/Vehicle/CMakeLists.txt:45 (add_executable):
   add_executable cannot create target "helloworld" because another target
   with the same name already exists.  The existing target is an executable
   created in source directory
   "/home/smso/Downloads/irrBullet/examples/HelloWorld".  See documentation
   for policy CMP0002 for more details.

**Comment by Deathsbreed** [comment]
I'm not sure if we've made this clear yet (probably not, sorry for that) but we've moved irrBullet to GitLab (https://gitlab.com/CollectiveTyranny/irrBullet). Check to see if it's been fixed there, if you still have issues I'll see what I can do (we've really got to delete this repo on GitHub).

**Comment by sosuiming** [comment]
I've made some changes to irrBullet.cmake, irrBulletKinematicCharacterController.cpp, irrBulletKinematicCharacterController.h and replaced all "BULLET_INCLUDE_DIRS" with "BULLET_INCLUDE_DIR" in all CMakeLists.txt files.

For irrBullet.cmake file:

[irrBulletKinematicCharacterController.h.txt](https://github.com/CollectiveTyranny/irrBullet/files/437563/irrBulletKinematicCharacterController.h.txt)
[irrBulletKinematicCharacterController.cpp.txt](https://github.com/CollectiveTyranny/irrBullet/files/437562/irrBulletKinematicCharacterController.cpp.txt)



  find_path(BULLET_INCLUDE_DIR
    NAMES
      #bullet3-2.83.7/src/btBulletCollisionCommon.h
      btBulletCollisionCommon.h
    PATHS
      /usr/local/include/bullet
  )
